spring:
  application:
    name: service1
  devtools:
    restart:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8082
server:
  port: 8089 #service0 占用8082
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 40000  # feign 超时控制
service0:
  ribbon:
    ReadTimeout: 100000
    ConnectTimeout: 50000
    MaxAutoRetries: 1  # SR6版本,这里设为1,会重试3次,重试次数还和另外的两个值有关


